source "https://github.com/feifu2023/ETSpecs.git"
source "https://github.com/CocoaPods/Specs.git"
use_frameworks!

platform :ios, '10.0'

target 'ETAxolotlKit_Example' do
  pod 'ETAxolotlKit', :path => '../'
end
